version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gym_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  users-service:
    build: ./apps/users-service
    depends_on:
      - postgres
    ports:
      - "3001:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: gym_db

  clients-service:
    build:
      context: ./apps/clients-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3002:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: gym_db

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
        VITE_CLIENTS_API_URL: http://localhost:3002
    depends_on:
      - users-service
      - clients-service
    ports:
      - "8080:80"

volumes:
  pgdata:
